export type DocumentRecord = {
  id: string
  title: string
  source: string
  date: string
  confidence: 'HIGH' | 'MODERATE' | 'LOW' | 'UNVERIFIED'
  type: string
  body: string
  redacted?: string
}

export type DecisionOption = {
  id: string
  title: string
  summary: string
  upside: string
  risk: string
  unknown: string
  shifts: Record<string, 'up' | 'down' | 'steady'>
}

export type Scenario = {
  id: string
  title: string
  year: string
  location: string
  region: string
  role: string
  difficulty: 'Measured' | 'Demanding' | 'Severe'
  duration: number
  mode: 'CRISIS' | 'NEGOTIATION' | 'ANALYSIS' | 'POLITICAL'
  kind: 'HISTORICAL' | 'SIMULATION'
  hook: string
  objective: string
  known: string[]
  believed: string[]
  unknown: string[]
  priorities: string[]
  advisers: { title: string; recommendation: string; argument: string; risk: string }[]
  documents: DocumentRecord[]
  options: DecisionOption[]
  outcome: string
  archives: string
  debate: string
  sources: { label: string; url: string }[]
}

const commonPriorities = [
  'Prevent uncontrolled escalation',
  'Protect civilian lives',
  'Preserve strategic leverage',
  'Maintain alliance cohesion',
  'Gain time for better intelligence',
]

const option = (id: string, title: string, summary: string, upside: string, risk: string, unknown: string, shifts: DecisionOption['shifts']): DecisionOption => ({ id, title, summary, upside, risk, unknown, shifts })

const historical = (...raw: unknown[]): Scenario => {
  const inferredRegions: Record<string, string> = {
    'polish-crisis': 'Europe', 'soviet-collapse': 'Europe / Eurasia', 'yom-kippur-war': 'Middle East',
    'bay-of-pigs': 'Americas', 'marshall-plan': 'Europe', 'pearl-harbor-intelligence': 'Pacific',
  }
  const values = raw.length === 20 ? [...raw.slice(0, 4), inferredRegions[String(raw[0])], ...raw.slice(4)] : raw
  const [id, title, year, location, region, role, difficulty, duration, mode, hook, objective, known, believed, unknown, documents, advisers, options, outcome, archives, debate, sources] = values
  return { id, title, year, location, region, role, difficulty, duration, mode, kind: 'HISTORICAL', hook, objective, known, believed, unknown, documents, advisers, options, outcome, archives, debate, sources, priorities: commonPriorities } as Scenario
}

const docs = (year: string, place: string, subject: string): DocumentRecord[] => [
  { id: 'assessment', title: 'Situation assessment', source: 'Policy Planning Staff', date: `${year} · 07:30`, confidence: 'HIGH', type: 'ASSESSMENT', body: `Confirmed reporting places ${subject} at the center of the present crisis. The immediate facts are clearer than the other side’s intentions.` },
  { id: 'cable', title: 'Diplomatic cable', source: `${place} mission`, date: `${year} · 09:10`, confidence: 'MODERATE', type: 'DIPLOMATIC', body: 'Local contacts warn that public resolve may conceal private flexibility. The window for a negotiated signal may be narrow.' },
  { id: 'military', title: 'Operational estimate', source: 'Joint planning group', date: `${year} · 11:40`, confidence: 'MODERATE', type: 'MILITARY', body: 'A limited action is feasible, but escalation pathways cannot be contained with confidence.', redacted: 'Command authorities and exact readiness remain ███████████.' },
  { id: 'press', title: 'Public climate brief', source: 'Open-source unit', date: `${year} · 13:05`, confidence: 'LOW', type: 'POLITICAL', body: 'Public reporting is fragmentary. A visible failure to respond could create domestic pressure before the intelligence picture improves.' },
]

const advisers = (action: string, diplomacy: string, wait: string): Scenario['advisers'] => [
  { title: 'SECURITY TEAM', recommendation: action, argument: 'Initiative may be lost if the present position becomes normalized.', risk: 'Action could trigger a response beyond the intended scope.' },
  { title: 'DIPLOMATIC TEAM', recommendation: diplomacy, argument: 'A controlled channel can test intent without surrendering every source of leverage.', risk: 'Delay may be read as division or weakness.' },
  { title: 'INTELLIGENCE DIRECTOR', recommendation: wait, argument: 'The largest strategic uncertainty remains the other side’s threshold for action.', risk: 'Additional certainty may arrive after the best moment to act.' },
]

const baseOptions = (a: string, b: string, c: string): DecisionOption[] => [
  option('pressure', a, 'Apply visible pressure while retaining room to adjust.', 'Signals resolve and preserves initiative.', 'The signal may be misread as preparation for a larger move.', 'Whether the other side can retreat without public loss.', { 'Escalation pressure': 'up', 'Strategic leverage': 'up', 'Available time': 'down' }),
  option('channel', b, 'Open a private channel tied to a limited public step.', 'Tests flexibility while reducing public commitment.', 'Private diplomacy may leak or be dismissed.', 'Whether counterparts can credibly deliver an agreement.', { 'Escalation pressure': 'down', 'Alliance cohesion': 'steady', 'Intelligence confidence': 'up' }),
  option('delay', c, 'Delay commitment while collecting additional information.', 'Improves the basis for a later choice.', 'The situation may change faster than the intelligence picture.', 'Whether waiting improves clarity or merely transfers initiative.', { 'Available time': 'down', 'Intelligence confidence': 'up', 'Strategic leverage': 'down' }),
]

export const scenarios: Scenario[] = [
  historical(
    'cuban-missile-crisis', 'The Cuban Missile Crisis', '1962', 'Washington, D.C.', 'Americas', 'National Security Adviser', 'Severe', 18, 'CRISIS',
    '13 days. Two nuclear superpowers. Incomplete information.',
    'Respond to the discovery of Soviet nuclear missiles in Cuba while protecting U.S. security and avoiding uncontrolled escalation.',
    ['U-2 photography shows Soviet medium-range ballistic missile sites under construction in Cuba.', 'Some launch positions could become operational quickly.', 'The President has convened a small executive committee.'],
    ['The deployment is intended to alter the strategic balance.', 'Moscow may expect Washington to accept the missiles as a fait accompli.'],
    ['Whether nuclear warheads are already on the island.', 'How Soviet commanders would respond to an attack.', 'Whether Moscow will trade the missiles for a political concession.'],
    [
      { id: 'u2', title: 'U-2 photographic interpretation', source: 'National Photographic Interpretation Center', date: '16 OCT 1962 · 08:45', confidence: 'HIGH', type: 'IMAGERY', body: 'Analysts identify launchers, missile transporters and construction consistent with medium-range ballistic missile sites near San Cristóbal.', redacted: 'Estimated operational status: ███████████.' },
      { id: 'intent', title: 'Estimate of Soviet intentions', source: 'Central Intelligence Agency', date: '16 OCT 1962 · 11:30', confidence: 'MODERATE', type: 'ASSESSMENT', body: 'The deployment represents a deliberate strategic gamble. The political objective remains uncertain; multiple interpretations remain plausible.' },
      { id: 'strike', title: 'Air strike planning note', source: 'Joint Chiefs planning staff', date: '16 OCT 1962 · 14:10', confidence: 'MODERATE', type: 'MILITARY', body: 'A concentrated strike could damage identified sites. Complete destruction cannot be assured.', redacted: 'Surviving capability and Soviet response: ███████████.' },
      { id: 'allies', title: 'Alliance consultation brief', source: 'Department of State', date: '16 OCT 1962 · 16:20', confidence: 'HIGH', type: 'DIPLOMATIC', body: 'Allies will expect evidence and consultation. Public disclosure without preparation could strain cohesion.' },
      { id: 'cuba', title: 'Cuba force posture', source: 'Defense Intelligence Agency', date: '17 OCT 1962 · 07:00', confidence: 'LOW', type: 'FIELD REPORT', body: 'Soviet personnel and air-defense units appear more numerous than earlier estimates. Rules of engagement are unknown.' },
      { id: 'domestic', title: 'Domestic political climate', source: 'White House legislative office', date: '17 OCT 1962 · 10:15', confidence: 'MODERATE', type: 'POLITICAL', body: 'Congressional pressure for a forceful response will rise sharply once the deployment becomes public.' },
      { id: 'moscow', title: 'Moscow communication analysis', source: 'Signals analysis unit', date: '17 OCT 1962 · 13:45', confidence: 'UNVERIFIED', type: 'SIGNALS', body: 'Traffic volume has increased. Analysts disagree whether this reflects operational urgency or routine reaction to U.S. surveillance.' },
    ],
    advisers('Prepare a surprise air strike against the missile sites.', 'Announce a naval quarantine and pair it with a private channel.', 'Continue surveillance before choosing a public course.'),
    [
      option('air-strike', 'Targeted air strikes', 'Attack identified missile and air-defense sites before they become fully operational.', 'May remove much of the immediate threat.', 'Incomplete destruction could trigger retaliation against Berlin or U.S. forces.', 'Whether Soviet nuclear warheads are already present and delegated.', { 'Escalation pressure': 'up', 'Alliance cohesion': 'down', 'Strategic leverage': 'up', 'Available time': 'down' }),
      option('quarantine', 'Naval quarantine', 'Intercept further offensive military shipments while demanding removal of existing missiles.', 'Creates pressure without immediately initiating combat.', 'A confrontation at sea could escalate and existing sites gain time.', 'How Moscow will interpret and test the line.', { 'Escalation pressure': 'up', 'Alliance cohesion': 'up', 'Strategic leverage': 'steady', 'Available time': 'down' }),
      option('private-deal', 'Private diplomatic approach', 'Offer a confidential path to withdrawal before public action.', 'Could resolve the crisis without a military encounter.', 'Delay may allow sites to become operational and a leak may look like weakness.', 'Whether Moscow sees the offer as an opening or a bluff.', { 'Escalation pressure': 'down', 'Alliance cohesion': 'steady', 'Intelligence confidence': 'steady', 'Available time': 'down' }),
      option('surveillance', 'Intensify surveillance', 'Collect more intelligence before committing to a course.', 'Reduces uncertainty about readiness and force levels.', 'Further flights could be challenged while missile construction continues.', 'Whether additional evidence will materially improve the choice.', { 'Escalation pressure': 'steady', 'Intelligence confidence': 'up', 'Strategic leverage': 'down', 'Available time': 'down' }),
    ],
    'The United States announced a naval “quarantine” on October 22. After several days of public and private exchanges, the Soviet Union agreed to remove the missiles; the United States publicly pledged not to invade Cuba and secretly agreed to remove Jupiter missiles from Turkey.',
    'Later evidence showed that Soviet tactical nuclear weapons were in Cuba and that local commanders had more operational latitude than U.S. decision-makers understood. This makes the uncertainty surrounding military options even more consequential.',
    'Historians continue to debate the relative weight of coercion, restraint, the secret Turkey arrangement, and the role of individual judgment in bringing the crisis to a close.',
    [
      { label: 'U.S. State Department — Office of the Historian', url: 'https://history.state.gov/milestones/1961-1968/cuban-missile-crisis' },
      { label: 'JFK Library — Cuban Missile Crisis', url: 'https://www.jfklibrary.org/learn/about-jfk/jfk-in-history/cuban-missile-crisis' },
      { label: 'National Security Archive — Cuban Missile Crisis', url: 'https://nsarchive.gwu.edu/briefing-book/cuba/2022-10-04/cuban-missile-crisis-60' },
    ],
  ),
  historical('berlin-blockade', 'Berlin Blockade', '1948', 'Berlin, Germany', 'Europe', 'Allied Policy Coordinator', 'Demanding', 12, 'CRISIS', 'A city is cut off. Every relief route is now a strategic signal.', 'Sustain West Berlin without turning access rights into a direct military confrontation.', ['Road, rail and canal access to western sectors is blocked.', 'Air corridors remain available.', 'Berlin’s civilian supplies are limited.'], ['The blockade is intended to force political concessions.', 'Moscow may avoid directly attacking unarmed transport aircraft.'], ['How long an air supply effort can be sustained.', 'Whether allied unity will survive mounting cost.'], docs('1948', 'Berlin', 'the blockade'), advisers('Organize an armed ground convoy.', 'Build a sustained airlift while protesting diplomatically.', 'Seek a temporary settlement before committing resources.'), baseOptions('Force a ground corridor', 'Begin a full-scale airlift', 'Seek a temporary access accord'), 'The Western Allies organized the Berlin Airlift. The Soviet Union lifted the blockade in May 1949, while the political division of Germany hardened.', 'The airlift’s scale and persistence transformed a logistical response into a demonstration of political commitment.', 'Debate continues over how much the blockade accelerated a division of Europe already under way.', [{ label: 'U.S. State Department — Berlin Airlift', url: 'https://history.state.gov/milestones/1945-1952/berlin-airlift' }]),
  historical('july-crisis', 'The July Crisis', '1914', 'Vienna, Austria-Hungary', 'Europe', 'Imperial Foreign Policy Adviser', 'Severe', 15, 'CRISIS', 'An assassination becomes a test of alliance credibility—and then something larger.', 'Respond to the Sarajevo assassination while limiting the risk of a general European war.', ['Archduke Franz Ferdinand has been assassinated.', 'Serbian-linked networks are suspected.', 'Germany signals support for Austria-Hungary.'], ['A limited move can remain localized.', 'Russia may hesitate if presented with a fait accompli.'], ['The exact limits of allied commitments.', 'How mobilization timetables will compress diplomacy.'], docs('1914', 'Vienna', 'the Serbian question'), advisers('Issue a hard ultimatum backed by force.', 'Coordinate a narrower demand with the powers.', 'Delay until the investigative record is stronger.'), baseOptions('Issue a maximal ultimatum', 'Seek a mediated settlement', 'Continue the investigation'), 'Austria-Hungary issued an ultimatum to Serbia; interlocking mobilizations and declarations of war followed, expanding the crisis into the First World War.', 'Diplomatic records later illustrated how military timetables, alliance expectations and misperception narrowed the space for restraint.', 'Historians dispute the distribution of responsibility and the degree to which leaders intended or merely accepted the risk of general war.', [{ label: 'International Encyclopedia of the First World War — July Crisis', url: 'https://encyclopedia.1914-1918-online.net/article/july_crisis_1914/' }]),
  historical('munich-crisis', 'Munich Crisis', '1938', 'London, United Kingdom', 'Europe', 'Prime Minister’s Foreign Policy Adviser', 'Severe', 14, 'NEGOTIATION', 'A territorial demand is presented as the price of peace.', 'Protect European security while deciding how to respond to German demands over the Sudetenland.', ['Germany demands transfer of the Sudeten territories.', 'Czechoslovakia has defenses and treaty relationships.', 'British public opinion strongly fears another war.'], ['A settlement might satisfy Germany’s final territorial claim.', 'France may not act without British support.'], ['Germany’s longer-term intentions.', 'Whether deterrence is still credible.'], docs('1938', 'London', 'the Sudeten dispute'), advisers('Coordinate military deterrence with France.', 'Negotiate a conditional territorial settlement.', 'Press Prague to concede immediately.'), baseOptions('Issue a joint deterrent warning', 'Negotiate with enforceable guarantees', 'Accept the proposed transfer'), 'The Munich Agreement permitted German annexation of the Sudetenland without Czechoslovak participation. Germany occupied the Czech lands in March 1939.', 'Subsequent records strengthened the view that Hitler’s aims extended beyond the Sudeten question, while also revealing the constraints perceived by British and French leaders.', 'Debate concerns available military alternatives, public readiness, and whether delay aided later resistance or only strengthened Germany.', [{ label: 'UK National Archives — The Munich Agreement', url: 'https://www.nationalarchives.gov.uk/education/resources/chamberlain-and-hitler/' }]),
  historical('able-archer', 'Able Archer', '1983', 'NATO Command, Brussels', 'Europe', 'NATO Intelligence Adviser', 'Severe', 11, 'ANALYSIS', 'An exercise looks routine from one side—and possibly real from the other.', 'Assess Warsaw Pact reactions to a NATO exercise without amplifying a dangerous misunderstanding.', ['Able Archer tests nuclear command procedures.', 'Soviet intelligence activity has increased.', 'Political relations are acutely tense.'], ['Moscow may view unusual procedures as cover for real action.', 'Some indicators could also be routine.'], ['How alarmed Soviet leaders actually are.', 'Which reassurance signals would be noticed.'], docs('1983', 'Brussels', 'exercise signaling'), advisers('Maintain the exercise exactly as planned.', 'Quietly reduce anomalous exercise features.', 'Pause while requesting more collection.'), baseOptions('Proceed without adjustment', 'Reduce provocative anomalies', 'Suspend the final exercise phase'), 'The exercise concluded without confrontation. Later evidence indicated significant Soviet concern, though the precise level of perceived danger remains contested.', 'Declassified documents showed that Western officials took Soviet fears more seriously after the exercise than many had at the time.', 'Scholars debate whether the episode represented a near miss or a serious scare contained by existing caution.', [{ label: 'National Security Archive — Able Archer 83', url: 'https://nsarchive.gwu.edu/briefing-book/nuclear-vault-russia-programs/2018-10-22/able-archer-83-sourcebook' }]),
  historical('prague-spring', 'Prague Spring', '1968', 'Prague, Czechoslovakia', 'Europe', 'Presidium Political Adviser', 'Severe', 13, 'POLITICAL', 'Reform has public momentum. The alliance sees strategic contagion.', 'Advance political reform while managing pressure from Warsaw Pact governments.', ['Censorship has eased and reform is accelerating.', 'Warsaw Pact leaders are issuing warnings.', 'Public expectations have risen rapidly.'], ['Limited reassurances may preserve room for reform.', 'Open resistance could unify external opponents.'], ['Whether intervention has already been authorized.', 'Which reforms Moscow considers irreversible.'], docs('1968', 'Prague', 'the reform program'), advisers('Mobilize visible resistance.', 'Offer alliance guarantees while preserving core reforms.', 'Slow the program to gain time.'), baseOptions('Defend the reform program publicly', 'Offer security reassurances', 'Temporarily slow implementation'), 'Warsaw Pact forces invaded Czechoslovakia in August 1968. Reform was reversed under a period of “normalization.”', 'Records show sustained pressure, internal division among allied states, and a Soviet leadership increasingly unwilling to tolerate political pluralization.', 'Debate persists over whether any feasible reassurance could have prevented intervention without abandoning the reform project.', [{ label: 'Wilson Center Digital Archive — Prague Spring', url: 'https://digitalarchive.wilsoncenter.org/topics/prague-spring-1968' }]),
  historical('suez-crisis', 'Suez Crisis', '1956', 'London, United Kingdom', 'Middle East', 'Cabinet Strategy Adviser', 'Severe', 14, 'CRISIS', 'A canal is nationalized. An empire must decide what power it still has.', 'Protect access and credibility while weighing legal, financial and alliance constraints.', ['Egypt has nationalized the Suez Canal Company.', 'France supports stronger action.', 'U.S. support for military action is uncertain.'], ['Pressure could force a settlement.', 'Inaction may accelerate loss of influence.'], ['The financial reaction to intervention.', 'How the Soviet Union and United States would respond.'], docs('1956', 'London', 'the canal crisis'), advisers('Coordinate military intervention.', 'Build an international users’ arrangement.', 'Accept nationalization with compensation talks.'), baseOptions('Prepare coordinated intervention', 'Internationalize negotiations', 'Negotiate compensation directly'), 'Britain, France and Israel attacked Egypt. International and financial pressure, especially from the United States, forced withdrawal.', 'The crisis exposed the limits of independent British and French power and elevated Nasser’s regional standing.', 'Historians debate the interaction of imperial decline, alliance management and domestic political judgment.', [{ label: 'U.S. State Department — Suez Crisis', url: 'https://history.state.gov/milestones/1953-1960/suez' }]),
  historical('korean-war', 'Korean War', '1950', 'Washington, D.C.', 'Asia', 'National Security Council Adviser', 'Severe', 15, 'CRISIS', 'An invasion tests a new security order. The limits of the war are undefined.', 'Respond to North Korea’s invasion while preventing a wider war in Asia.', ['North Korean forces have crossed the 38th parallel.', 'South Korean defenses are under severe pressure.', 'The UN Security Council can act in the Soviet absence.'], ['A firm response may deter wider challenges.', 'China may avoid direct intervention.'], ['The Soviet role in operational decisions.', 'The threshold that would trigger Chinese entry.'], docs('1950', 'Washington', 'the Korean invasion'), advisers('Commit forces to restore the line.', 'Limit action to air and logistical support.', 'Seek an immediate ceasefire channel.'), baseOptions('Commit ground forces under UN command', 'Provide limited military support', 'Prioritize a ceasefire initiative'), 'A U.S.-led UN force intervened. The war expanded after forces crossed the 38th parallel and China entered; an armistice was signed in 1953.', 'Captured and declassified materials illuminated the roles of Moscow and Beijing, while showing that intentions changed over the course of the war.', 'Debate centers on deterrence, escalation, the decision to advance north, and alternatives to a prolonged war.', [{ label: 'U.S. State Department — Korean War', url: 'https://history.state.gov/milestones/1945-1952/korean-war-2' }]),
  historical('iranian-revolution', 'Iranian Revolution', '1979', 'Washington, D.C.', 'Middle East', 'Presidential Foreign Policy Adviser', 'Demanding', 12, 'POLITICAL', 'A long-standing ally is losing control. Every signal changes the opposition’s calculation.', 'Protect citizens and strategic interests while assessing the durability of Iran’s government.', ['Mass protests have expanded.', 'The Shah’s authority and health are uncertain.', 'The opposition contains diverse factions.'], ['The armed forces may preserve order.', 'Visible U.S. support could either reassure or delegitimize.'], ['Who could command a transitional coalition.', 'Whether coercion would restore order or accelerate collapse.'], docs('1979', 'Tehran', 'the political transition'), advisers('Back the existing government visibly.', 'Open channels across the opposition.', 'Prepare evacuation and avoid public alignment.'), baseOptions('Reaffirm support for the Shah', 'Broaden political contacts', 'Adopt public neutrality'), 'The Shah left Iran in January 1979; Ayatollah Khomeini returned, and the monarchy collapsed. A new Islamic Republic consolidated power amid intense political struggle.', 'Documents reveal persistent uncertainty inside the U.S. government about the stability of the monarchy and the character of the opposition.', 'Debate continues over external influence, missed diplomatic openings, and the range of viable U.S. options.', [{ label: 'U.S. State Department — Iran, 1977–1980', url: 'https://history.state.gov/historicaldocuments/frus1977-80v10' }]),
  historical('polish-crisis', 'Polish Political Crisis', '1980–1981', 'Warsaw, Poland', 'Government Negotiation Adviser', 'Severe', 15, 'POLITICAL', 'A mass movement has bargaining power. The state has coercive power. Moscow is watching.', 'Manage confrontation with Solidarity while avoiding violence, economic collapse and external intervention.', ['Solidarity has millions of members.', 'The economy is in deep crisis.', 'Warsaw Pact pressure is growing.'], ['Some accommodation may stabilize the system.', 'Moscow may intervene if party control appears at risk.'], ['The true threshold for Soviet action.', 'Whether negotiations can produce durable restraint.'], docs('1981', 'Warsaw', 'the Solidarity confrontation'), advisers('Prepare emergency rule.', 'Negotiate a limited institutional settlement.', 'Delay while seeking economic relief.'), baseOptions('Prepare martial law', 'Offer structured negotiations', 'Delay and seek external economic support'), 'Polish authorities imposed martial law in December 1981, suppressing Solidarity’s legal activity. The movement survived underground and returned to negotiations later in the decade.', 'Later evidence complicated contemporary fears of an imminent Soviet invasion while confirming strong external pressure and internal contingency planning.', 'Debate remains over the necessity claimed by the authorities, the likelihood of intervention, and the alternatives available.', [{ label: 'Wilson Center Digital Archive — Polish Crisis', url: 'https://digitalarchive.wilsoncenter.org/topics/polish-crisis-1980-1981' }]),
  historical('soviet-collapse', 'Collapse of the Soviet Union', '1991', 'Moscow, USSR', 'Union Policy Adviser', 'Severe', 14, 'POLITICAL', 'Institutions are dissolving faster than authority can be reassigned.', 'Navigate constitutional, economic and security risks as union republics assert sovereignty.', ['The August coup has failed.', 'Republican leaders have gained authority.', 'The economy and chain of command are deteriorating.'], ['A renewed union treaty may still be possible.', 'Rapid dissolution could create uncontrolled security risks.'], ['Who controls nuclear forces during transition.', 'Whether economic coordination can survive political separation.'], docs('1991', 'Moscow', 'the union crisis'), advisers('Centralize emergency authority.', 'Negotiate a loose confederation.', 'Recognize dissolution and focus on controlled transition.'), baseOptions('Reassert central authority', 'Negotiate a new union compact', 'Plan an orderly dissolution'), 'The Soviet Union dissolved in December 1991 after leaders of Russia, Ukraine and Belarus declared it had ceased to exist and established the Commonwealth of Independent States.', 'Subsequent records underscored the speed of institutional collapse and the importance of arrangements governing nuclear weapons and succession.', 'Debate concerns economic reform, nationalism, institutional failure and whether a looser union remained possible.', [{ label: 'Library of Congress — Soviet Union: A Country Study', url: 'https://www.loc.gov/item/96019284/' }]),
  historical('yom-kippur-war', 'Yom Kippur War', '1973', 'Jerusalem, Israel', 'National Intelligence Adviser', 'Severe', 13, 'ANALYSIS', 'Warning indicators accumulate—but they conflict with the prevailing concept.', 'Assess Egyptian and Syrian military preparations before the cost of being wrong changes abruptly.', ['Egyptian and Syrian forces are exercising near ceasefire lines.', 'Some reserves and equipment have moved forward.', 'Previous alerts did not lead to war.'], ['Arab states are unlikely to attack without air superiority.', 'Mobilization may be political signaling.'], ['Whether leaders accept military risk for limited aims.', 'Whether source reporting reflects genuine warning.'], docs('1973', 'Jerusalem', 'Arab force movements'), advisers('Recommend immediate mobilization.', 'Issue a warning and begin discreet preparations.', 'Maintain collection without public action.'), baseOptions('Recommend full mobilization', 'Begin limited readiness measures', 'Hold the current posture'), 'Egypt and Syria attacked on October 6, 1973. Israel recovered militarily after early setbacks; the war reshaped regional diplomacy and led eventually to Egyptian-Israeli negotiations.', 'Postwar inquiries examined analytic assumptions and the failure to interpret warning indicators outside the prevailing concept.', 'Debate continues over the balance between intelligence failure, policy assumptions and the feasibility of earlier mobilization.', [{ label: 'CIA — The 1973 Arab-Israeli War', url: 'https://www.cia.gov/readingroom/collection/president-nixon-and-role-intelligence-1973-arab-israeli-war' }]),
  historical('bay-of-pigs', 'Bay of Pigs', '1961', 'Washington, D.C.', 'Presidential Security Adviser', 'Severe', 12, 'CRISIS', 'A covert plan reaches the point where secrecy and success are no longer compatible.', 'Evaluate an inherited invasion plan while weighing deniability, escalation and the strength of the Cuban government.', ['A CIA-backed exile force is training.', 'The plan depends on local uprising and limited visibility.', 'Air support is politically constrained.'], ['The landing may trigger defections.', 'U.S. involvement can remain plausibly deniable.'], ['The strength of Castro’s internal support.', 'Whether the beachhead can survive without overt U.S. action.'], docs('1961', 'Washington', 'the exile invasion plan'), advisers('Approve the operation with stronger support.', 'Scale down and test political conditions.', 'Cancel the landing.'), baseOptions('Approve with expanded air cover', 'Postpone and reassess', 'Cancel the operation'), 'The exile force landed at the Bay of Pigs in April 1961 and was defeated within days. U.S. involvement quickly became evident.', 'Subsequent investigations found flawed assumptions, planning weaknesses and ambiguous decision processes across the operation.', 'Debate concerns presidential responsibility, intelligence assessment and whether any version of the operation could have achieved its political objectives.', [{ label: 'JFK Library — Bay of Pigs', url: 'https://www.jfklibrary.org/learn/about-jfk/jfk-in-history/the-bay-of-pigs' }]),
  historical('marshall-plan', 'Marshall Plan', '1947', 'Washington, D.C.', 'Economic Strategy Adviser', 'Demanding', 12, 'POLITICAL', 'Economic recovery is becoming a security policy.', 'Design a European recovery initiative that is politically sustainable and strategically credible.', ['European production and trade remain severely disrupted.', 'U.S. resources and public support are not unlimited.', 'Soviet participation is uncertain.'], ['Coordinated recovery can reduce political instability.', 'Congress will demand burden-sharing and oversight.'], ['The scale of assistance required.', 'How Moscow will respond to an open offer.'], docs('1947', 'Washington', 'European recovery'), advisers('Offer a large coordinated program.', 'Provide bilateral assistance to key states.', 'Limit commitments until European plans are clearer.'), baseOptions('Launch a multilateral recovery program', 'Prioritize bilateral aid', 'Delay pending detailed national requests'), 'The European Recovery Program supplied extensive U.S. aid beginning in 1948 and encouraged European coordination. The Soviet Union and Eastern European states did not participate.', 'The program’s implementation connected economic reconstruction with an emerging Western political order.', 'Historians debate the relative importance of humanitarian, economic and strategic motivations, as well as the program’s role in Cold War division.', [{ label: 'U.S. State Department — Marshall Plan', url: 'https://history.state.gov/milestones/1945-1952/marshall-plan' }]),
  historical('pearl-harbor-intelligence', 'Pearl Harbor Intelligence', '1941', 'Washington, D.C.', 'Naval Intelligence Analyst', 'Severe', 13, 'ANALYSIS', 'The warning is real. The target is not clear.', 'Synthesize fragmentary indicators of Japanese intent and recommend protective action without knowing the point of attack.', ['U.S.–Japanese negotiations are failing.', 'Intercepted communications indicate urgency.', 'Japanese forces are moving in several theaters.'], ['The main thrust may be toward Southeast Asia.', 'A direct attack on Hawaii appears operationally difficult.'], ['The exact location of major carrier forces.', 'The timing and target of hostilities.'], docs('1941', 'Washington', 'Japanese operational intent'), advisers('Issue a broad war warning and disperse forces.', 'Prioritize reinforcement of the Philippines.', 'Continue collection before disrupting readiness.'), baseOptions('Issue a high-priority general alert', 'Concentrate on Southeast Asia', 'Seek confirmation before escalating readiness'), 'Japan attacked Pearl Harbor on December 7, 1941, drawing the United States into the Second World War.', 'Investigations documented fragmented intelligence, organizational barriers and assumptions that shaped how warning was interpreted and distributed.', 'Debate concerns the allocation of responsibility among commanders, intelligence organizations and senior policymakers without supporting conspiracy claims.', [{ label: 'U.S. Senate — Pearl Harbor Investigation', url: 'https://www.senate.gov/about/powers-procedures/investigations/pearl-harbor.htm' }]),
]

export const simulations: Scenario[] = [
  {
    id: 'the-strait', title: 'The Strait', year: 'Near Future', location: 'The Meridien Strait', region: 'Indo-Pacific', role: 'National Security Adviser', difficulty: 'Severe', duration: 14, mode: 'CRISIS', kind: 'SIMULATION',
    hook: 'A stronger neighbor is testing a small ally—one patrol at a time.', objective: 'Deter coercion without turning a maritime standoff into a wider conflict.',
    known: ['A survey vessel has entered disputed waters with coast guard escort.', 'Your ally requests visible support.', 'Commercial shipping remains open.'], believed: ['The operation is designed to test alliance credibility.', 'Neither side currently seeks a shooting war.'], unknown: ['Whether the survey vessel will remain.', 'How much risk your ally will accept.'], priorities: commonPriorities,
    documents: docs('D+1', 'Embassy Meridien', 'the maritime incursion'), advisers: advisers('Deploy a naval escort.', 'Build a multilateral patrol and open a hotline.', 'Monitor without changing force posture.'), options: baseOptions('Deploy an escort', 'Assemble a multilateral patrol', 'Maintain strategic ambiguity'),
    outcome: 'This is a counterfactual simulation. Its branches illustrate strategic trade-offs, not predictions.', archives: 'No archival reveal is available for a fictional exercise. Hidden actor priorities are disclosed instead: the stronger state sought a visible concession but wanted to avoid an exchange of fire.', debate: 'The exercise leaves open whether reassurance and deterrence can be credibly combined when alliance commitments are deliberately ambiguous.', sources: [],
  },
  {
    id: 'the-coalition', title: 'The Coalition', year: 'Near Future', location: 'Republic of Norland', region: 'Europe', role: 'Coalition Negotiator', difficulty: 'Demanding', duration: 10, mode: 'NEGOTIATION', kind: 'SIMULATION',
    hook: 'The government lost its majority. The reform vote is in seventy-two hours.', objective: 'Build a viable majority without hollowing out the reform or exhausting political capital.',
    known: ['Three parties can supply the necessary votes.', 'Each has a different public demand.', 'The budget window closes this week.'], believed: ['At least one public red line is negotiable.', 'Bundling issues may create room for agreement.'], unknown: ['Which party values committee control most.', 'Whether a private offer will remain private.'], priorities: ['Pass the reform', 'Preserve coalition stability', 'Limit fiscal cost', 'Protect institutional legitimacy', 'Maintain a governing majority'],
    documents: docs('D−3', 'Parliament', 'the coalition vote'), advisers: advisers('Offer targeted concessions to the regional party.', 'Bundle oversight and timetable concessions.', 'Delay the vote and rebuild the package.'), options: baseOptions('Trade regional funding for votes', 'Bundle oversight and timing concessions', 'Postpone the vote'),
    outcome: 'This is a counterfactual simulation. The result models coalition incentives, not a forecast.', archives: 'The Green Alliance values a binding review clause more than a ministerial post. The regional party’s funding demand is partly a signal to its own voters.', debate: 'The strategic question is not only whether a deal passes, but what kind of governing relationship it creates afterward.', sources: [],
  },
  {
    id: 'the-blackout', title: 'The Blackout', year: 'Near Future', location: 'North Atlantic Alliance', region: 'Europe', role: 'Intelligence Coordinator', difficulty: 'Severe', duration: 11, mode: 'ANALYSIS', kind: 'SIMULATION',
    hook: 'Three grids fail in ninety minutes. Attribution is still an assessment.', objective: 'Coordinate recovery and signaling while the evidence for responsibility remains incomplete.',
    known: ['Grid operators report coordinated malicious access.', 'Hospitals are using backup power.', 'An allied minister has publicly named a suspect.'], believed: ['The attack required state-level preparation.', 'Some evidence may have been planted.'], unknown: ['Whether a second wave is prepared.', 'Who directed the operation.'], priorities: commonPriorities,
    documents: docs('H+2', 'Alliance Cyber Cell', 'the infrastructure attack'), advisers: advisers('Attribute publicly and announce consequences.', 'Share evidence privately and coordinate resilience.', 'Avoid attribution until technical confidence improves.'), options: baseOptions('Publicly attribute the attack', 'Coordinate a private allied warning', 'Delay attribution'),
    outcome: 'This is a counterfactual simulation. Later branches depend on both technical findings and how public claims change the diplomatic environment.', archives: 'The strongest technical indicator was genuine, but a conspicuous code signature was planted to accelerate blame.', debate: 'The exercise asks how much confidence should be required for public attribution when delay also carries costs.', sources: [],
  },
]

export const allScenarios = [...scenarios, ...simulations]
